services:
  - type: web
    name: swa-backend
    rootDir: backend
    runtime: node
    branch: main
    region: ohio
    plan: free
    
    buildCommand: "npm install"
    startCommand: "node src/index.js"

    envVars:
      - key: PORT
        value: 4000

      - key: MONGO_URI
        sync: false

      - key: JWT_SECRET
        sync: false

      - key: EMAIL_USER
        sync: false

      - key: EMAIL_PASS
        sync: false

      - key: BACKEND_URL
        sync: false

      - key: FRONTEND_URL
        sync: false

      - key: CLOUDINARY_CLOUD_NAME
        sync: false

      - key: CLOUDINARY_API_KEY
        sync: false

      - key: CLOUDINARY_API_SECRET
        sync: false
